"""add_task_optimization_link

Revision ID: 2da4764a7206
Revises: 768ff20099d4
Create Date: 2026-03-21 09:42:59.024536
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2da4764a7206'
down_revision: Union[str, None] = '768ff20099d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_tasks', sa.Column('agent_optimization_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'ai_tasks', 'agent_optimizations', ['agent_optimization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_tasks', type_='foreignkey')
    op.drop_column('ai_tasks', 'agent_optimization_id')
    # ### end Alembic commands ###
