"""initial_schema

Revision ID: 47a867ce7b9a
Revises: 
Create Date: 2026-03-21 09:14:33.419814
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '47a867ce7b9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('live_key_hash', sa.String(length=255), nullable=False),
    sa.Column('live_key_prefix', sa.String(length=30), nullable=False),
    sa.Column('test_key_hash', sa.String(length=255), nullable=False),
    sa.Column('test_key_prefix', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('rate_limits', sa.JSON(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('agent_training_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_training_data_agent_type'), 'agent_training_data', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_training_data_source_type'), 'agent_training_data', ['source_type'], unique=False)
    op.create_index(op.f('ix_agent_training_data_tenant_id'), 'agent_training_data', ['tenant_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_agent_type'), 'ai_conversations', ['agent_type'], unique=False)
    op.create_index(op.f('ix_ai_conversations_external_user_id'), 'ai_conversations', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_tenant_id'), 'ai_conversations', ['tenant_id'], unique=False)
    op.create_table('token_usage_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('driver', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_logs_log_date'), 'token_usage_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_tenant_id'), 'token_usage_logs', ['tenant_id'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('tone_attributes', sa.JSON(), nullable=True),
    sa.Column('system_modifier', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_tenant_id'), 'voice_profiles', ['tenant_id'], unique=False)
    op.create_table('ai_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('driver_used', sa.String(length=50), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tasks_agent_type'), 'ai_tasks', ['agent_type'], unique=False)
    op.create_index(op.f('ix_ai_tasks_conversation_id'), 'ai_tasks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_tasks_external_user_id'), 'ai_tasks', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_ai_tasks_status'), 'ai_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_ai_tasks_tenant_id'), 'ai_tasks', ['tenant_id'], unique=False)
    op.create_table('agent_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ai_task_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('signal', sa.String(length=20), nullable=False),
    sa.Column('user_edit', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_task_id'], ['ai_tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_feedback_agent_type'), 'agent_feedback', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_feedback_ai_task_id'), 'agent_feedback', ['ai_task_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_tenant_id'), 'agent_feedback', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_feedback_tenant_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_ai_task_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_agent_type'), table_name='agent_feedback')
    op.drop_table('agent_feedback')
    op.drop_index(op.f('ix_ai_tasks_tenant_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_status'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_external_user_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_conversation_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_agent_type'), table_name='ai_tasks')
    op.drop_table('ai_tasks')
    op.drop_index(op.f('ix_voice_profiles_tenant_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_token_usage_logs_tenant_id'), table_name='token_usage_logs')
    op.drop_index(op.f('ix_token_usage_logs_log_date'), table_name='token_usage_logs')
    op.drop_table('token_usage_logs')
    op.drop_index(op.f('ix_ai_conversations_tenant_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_external_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_agent_type'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_agent_training_data_tenant_id'), table_name='agent_training_data')
    op.drop_index(op.f('ix_agent_training_data_source_type'), table_name='agent_training_data')
    op.drop_index(op.f('ix_agent_training_data_agent_type'), table_name='agent_training_data')
    op.drop_table('agent_training_data')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
