"""add_tenant_webhook_url

Revision ID: 768ff20099d4
Revises: a1903e9755c5
Create Date: 2026-03-21 09:42:29.722656
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '768ff20099d4'
down_revision: Union[str, None] = 'a1903e9755c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('webhook_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'webhook_url')
    # ### end Alembic commands ###
