"""add_raw_key_to_api_keys

Revision ID: c80bc972b19c
Revises: d5f2b8a93e17
Create Date: 2026-04-04 18:34:20.609715
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c80bc972b19c'
down_revision: Union[str, None] = 'd5f2b8a93e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('raw_key', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_api_keys_tier'), table_name='api_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_keys_tier'), 'api_keys', ['tier'], unique=False)
    op.drop_column('api_keys', 'raw_key')
    # ### end Alembic commands ###
