"""Agent Optimization model — tracks evolved prompt versions."""

from sqlalchemy import BigInteger, Boolean, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin


class AgentOptimization(Base, TimestampMixin):
    """
    Stores evolved versions of agent prompts generated by the Meta-Optimizer.
    
    Software Factory: prompts are no longer static YAML; they are living, 
    versioned assets in the database.
    """
    __tablename__ = "agent_optimizations"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    agent_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    
    # The actual optimized prompt text
    prompt_text: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Metadata for review
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    
    def __repr__(self) -> str:
        return f"<AgentOptimization {self.agent_type} v{self.version} active={self.is_active}>"
